<?php
$aluno["nome"] = "Marciel Cena";
$aluno["endereco"] = "Rua D";
$aluno["cidade"] = "kaitite";
$aluno["estado"] = "Bahia";
$aluno["idade"] = "12";
$aluno["cpf"] = "234.646.676-35";
echo "nome : ".$aluno["nome"] ."<br>"."endereco : ". $aluno["endereco"]."<br>". "cidade : ". $aluno["cidade"]."<br>". "estado : ". $aluno["estado"] ."<br>"."idade : ".$aluno["idade"]  ."<br>"."CPF : ".$aluno["cpf"];
echo "<br>";
echo "<br>";
$aluno["nome"] = "Darius Muzafar";
$aluno["endereco"] = "Rua R";
$aluno["cidade"] = "kaitite";
$aluno["estado"] = "Bahia";
$aluno["idade"] = "34";
$aluno["cpf"] = "334.564.545-04";
echo "nome : ".$aluno["nome"] ."<br>"."endereco : ". $aluno["endereco"]."<br>". "cidade : ". $aluno["cidade"]."<br>". "estado : ". $aluno["estado"] ."<br>"."idade : ".$aluno["idade"]  ."<br>"."CPF : ".$aluno["cpf"];
echo "<br>";
echo "<br>";
$aluno["nome"] = "Mariane Rocha";
$aluno["endereco"] = "Rua rio branco";
$aluno["cidade"] = "Itauna";
$aluno["estado"] = "Minas Gerais";
$aluno["idade"] = "23";
$aluno["cpf"] = "112.365.363-06";
echo "nome : ".$aluno["nome"] ."<br>"."endereco : ". $aluno["endereco"]."<br>". "cidade : ". $aluno["cidade"]."<br>". "estado : ". $aluno["estado"] ."<br>"."idade : ".$aluno["idade"]  ."<br>"."CPF : ".$aluno["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "Castro";
$professor["endereco"] = "Rua Rc";
$professor["cidade"] = "Ibirite";
$professor["estado"] = "Minas Gerais";
$professor["idade"] = "20";
$professor["cpf"] = "089.043.032-32";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "Naldo Pires";
$professor["endereco"] = "Rua Pitangas";
$professor["cidade"] = "igarape";
$professor["estado"] = "Minas Gerais";
$professor["idade"] = "56";
$professor["cpf"] = "890.932.345-07";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "Joares Tulho";
$professor["endereco"] = "Rua luiz peixoto";
$professor["cidade"] = "Beti";
$professor["estado"] = "Minas Gerais";
$professor["idade"] = "54";
$professor["cpf"] = "980.327.438-09";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "Analho LOpes";
$professor["endereco"] = "Rua mechilao";
$professor["cidade"] = "Sao Paulo";
$professor["estado"] = "Sao Paulo";
$professor["idade"] = "42";
$professor["cpf"] = "048.390.232-08";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
